org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

# Minecraft / NeoForge
minecraft_version=26.3
neoforge_version=26.3.0.1-beta

# Mod properties
mod_version=1.7.0
maven_group=com.breakinblocks.neosync
archives_base_name=NeoSync
mod_id=neosync
mod_author=BreakinBlocks

# Dependencies
mixinextras_version=0.4.1

# Integration deps
jei_version=31.0.0.5
jade_version=26.3.1+neoforge
curios_version=16.0.0+26.2

# Publishing
curseforge_project_id=1521718
modrinth_project_id=QJvmrm6D
